export const FETCH_BETS = 'BETSLIP::FETCH_BETS'
export const FETCH_BETS_SUCCESS = 'BETSLIP::FETCH_BETS::SUCCESS'
export const FETCH_BETS_ERROR = 'BETSLIP::FETCH_BETS::ERROR'

export const ON_CHANGE_STAKE = 'BETSLIP::ON_CHANGE_STAKE'
export const ON_SUBMIT = 'BETSLIP::ON_SUBMIT'
